#Directories 
results_dir: #absolute path to the results directory
working_dir: #absolute path for working directory

#List of samples (in tsv format)
units:  #Provide local path to where the "units" file is stored containing sample IDs and input ids

#Mitochondrial reference sequence
chrM_refseq: mtDNA_variant_calling_pipeline/chrM_reference/chrMref.fa

#Rule parameters

##Parameters for specifying # of threads, other resources for runnign rules
# rule_resources:
#   threads: 1 #Default: 1

